// src/pages/index.tsx
import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { api } from "~/utils/api";
import type { Post } from "../types";  // Adjust the path if needed

export default function Home() {
  const { isSignedIn } = useUser();

  // Explicitly type the data returned from the API
  const { data, error } = api.post.getLatest.useQuery();

  if (error) {
    console.error("Failed to fetch data", error);
    return <div>Error fetching data</div>;  // Handle the error
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>

          <div className="flex flex-col items-center gap-4">
            <h2 className="text-2xl font-semibold text-white"></h2>
            <div className="px-4 py-2 font-semibold text-white bg-blue-500 rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:ring-opacity-75">
              {!isSignedIn && <SignInButton />}
              {isSignedIn && <SignOutButton />}
            </div>
          </div>

          {/* Render the data from the API */}
          <div className="flex flex-col items-center gap-4">
            {Array.isArray(data) ? (
              data.map((post: Post) => (
                <div key={post.id} className="text-white">
                  {post.title}
                </div>
              ))
            ) : (
              <div className="text-white">Suck a dick</div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}